---
- name: Stop "{{ zookeeper_docker_container_name }}"
  docker_container:
    name: "{{ zookeeper_docker_container_name }}"
    state: stopped
  ignore_errors: yes

- name: Remove "{{ zookeeper_docker_container_name }}"
  docker_container:
    name: "{{ zookeeper_docker_container_name }}"
    state: absent
  ignore_errors: yes

- name: Pull the Docker image with the name '{{ zookeeper_docker_image }}'
  docker_image:
    name: "{{ zookeeper_docker_image }}"

- name: Run the Docker image with the name '{{ zookeeper_docker_image }}'
  docker_container:
    name: "{{ zookeeper_docker_container_name }}"
    image: "{{ zookeeper_docker_image }}"
    published_ports: "{{ zookeeper_exposed_port }}:{{ zookeeper_internal_port }}"



- name: get container status
  shell: docker inspect "{{ zookeeper_docker_container_name }}"
  register: status

- name: Set container status as json from message output
  set_fact:
    statusJson: "{{ status.stdout | from_json }}"

- name: Set container state variable
  set_fact:
    containerState: "{{ statusJson[0] }}"

- name: Assert that "{{ zookeeper_docker_container_name }}" is running
  assert:
    that:
      - "{{ containerState.State.Running}} == true"
- name: Assert that "{{ zookeeper_docker_container_name }}" did not restart
  assert:
    that:
      - "{{ containerState.State.Restarting}} == false"
