---
- name: Download and install vault binary
  unarchive:
      src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
      dest: /usr/bin/
      remote_src: True



- name: Create vault config directory
  file: state=directory path=/etc/opt/vault/
  become: true

- name: Copy vault config to server
  copy: src=templates/vaultconfig.hcl dest=/etc/opt/vault/
  become: true

- name: run vault
  shell: nohup /usr/bin/vault server -config=/etc/opt/vault/vaultconfig.hcl  </dev/null >/dev/null 2>&1 &
  async: 10
  poll: 0