
---
- name: 1.Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: 2.Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists

- name: 3.Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest


- name: upgrade all packages
  yum: name=* state=latest
  ignore_errors: true
  no_log: true

- lineinfile:
    path: /etc/yum.conf
    regexp: '^obsoletes='
    line: 'obsoletes=0'
    owner: root
    group: root
    mode: 0644

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Install pip
  yum:
    name: python-pip
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: yes

- name: Removing selinux
  command: yum remove docker-ce-selinux -y

- name: Download container-docker-ce package
  command: yum install -y {{ dockerCeURL }}
  ignore_errors: yes

- name: Install Docker CE
  yum:
    name: docker-ce
    state: latest

- name: Install Docker-py
  command: pip install docker-py

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
